[package]
name = "uptime-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.uptime]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.57.1"
default-features = false
