// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    uptime
    (
        init => init
        upgrade => upgrade
        heartbeat => heartbeat_endpoint
        getLifetimeInfo => get_lifetime_info
        getHeartbeatCount => heartbeat_count
        getLastHeartbeatTimestamp => last_heartbeat_timestamp
        getLifetimeCount => lifetime_count
        getTotalHeartbeats => total_heartbeats_global
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
